### Numpy 的random有哪些應用

https://www.perplexity.ai/search/0eafd6c8-1230-4d5d-9553-446ea1f18997

In [1]:
### 學生成績單

import numpy as np
import pandas as pd

scores = np.random.randint(50, 101, size=(50, 5))
scores

array([[ 56,  70,  77,  83,  89],
       [ 72,  70,  87,  54,  51],
       [ 82,  92,  55,  68,  57],
       [ 59,  81,  90,  80,  71],
       [ 82, 100,  74,  81,  76],
       [ 62,  60,  70,  53,  85],
       [100,  99,  94,  52,  89],
       [ 70,  78,  69,  88,  74],
       [ 97,  59,  51,  61,  90],
       [ 92,  71,  93,  93,  92],
       [ 92,  58,  56,  70,  75],
       [ 55,  52,  95,  58,  88],
       [ 91,  54,  81,  99,  99],
       [ 73,  94,  67,  94,  77],
       [ 94,  96,  54,  68,  60],
       [ 69,  85,  97,  79,  73],
       [ 75,  50,  93,  73,  79],
       [ 84, 100,  67,  88,  64],
       [ 78,  93,  51,  77,  63],
       [ 77,  70, 100,  55,  71],
       [ 78,  58,  61,  88,  70],
       [ 53,  61,  81,  89,  58],
       [ 72,  78,  67,  59,  64],
       [ 88,  76,  64,  91,  61],
       [100,  65,  96,  85,  91],
       [ 71,  65,  71,  61,  76],
       [ 73,  69,  99,  81,  72],
       [ 76,  52,  70, 100,  83],
       [ 61,  91,  60,  76,  80],
       [ 56,  94,  68,  53,  53],
       [ 58,  94,  59,  97,  94],
       [ 84,  63,  54,  93,  99],
       [ 82, 100,  91,  83,  84],
       [ 64,  78,  78,  99,  96],
       [ 58,  58,  65,  90,  82],
       [ 62,  64,  92,  88,  59],
       [ 77,  68,  94, 100,  55],
       [ 53,  68,  57,  62,  85],
       [ 80,  79,  79,  93,  70],
       [ 62,  66,  94,  77,  79],
       [ 85,  66,  71, 100,  88],
       [ 72,  90,  73,  59,  52],
       [ 52,  77,  99,  53,  61],
       [ 65,  57,  54,  59,  97],
       [ 70,  73,  55,  65,  64],
       [ 61,  81,  53,  90,  70],
       [ 78, 100,  62,  59,  80],
       [ 94,  80,  72,  56,  97],
       [ 88,  84,  64,  86,  98],
       [ 58, 100,  64,  76,  93]], dtype=int32)

In [2]:
### 學生成績單

import numpy as np
import pandas as pd

scores = np.random.randint(50, 101, size=(50, 5))
scores_pd = pd.DataFrame(scores,columns=['國文','英文','數學','地理','歷史'],index=range(1,51))
scores_pd.T

,1,2,3,4,5,6,7,8,9,10,...,41,42,43,44,45,46,47,48,49,50
國文,66,62,54,63,71,73,75,68,61,70,...,67,82,65,55,91,65,63,80,51,55
英文,90,84,53,88,70,87,98,68,77,89,...,69,96,91,81,56,63,73,55,76,63
數學,68,81,89,69,98,93,56,55,80,66,...,56,87,81,69,91,62,97,59,94,78
地理,73,60,64,99,95,85,50,88,56,73,...,87,97,99,56,87,57,92,86,94,59
歷史,53,94,76,91,96,88,81,83,51,100,...,100,94,60,64,67,92,60,58,80,74